# Generated by Django 2.2.19 on 2022-04-11 21:46

import django.db.models.deletion
from django.db import migrations, models

import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220317_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Сообщество, к которому будет относиться пост', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_list', to='posts.Group', verbose_name='Сообщество'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Напишите о чем хотели рассказать', validators=[posts.validators.validate_not_empty], verbose_name='Содержание заметки'),
        ),
    ]
